export const invitationCopy = {
  copyButton: "Copy link",
  copied: "Invitation link copied. Share it privately with the invited person.",
  copyUnavailable: "Automatic copying is unavailable. Select and copy the link above.",
  createButton: "Create invitation link",
  created: "Invitation created. Copy and share its link privately.",
  createFailed: "The invitation could not be created. Try again.",
  creating: "Creating…",
  expires: "Expires",
  linkLabel: "Invitation link",
  linkCreated: "Invitation created. Copy this link now; it will not be shown again.",
  linkRegion: "New invitation link",
  linkShareHint: "Share through a private channel. If this link is lost, revoke the pending Invitation and create a new one.",
  missingToken: "No invitation token is present. If you just verified your email, reopen the original private invitation link to finish.",
  representative: "Representative",
  restoreUniversityBeforeInvite: "Restore this Member University before creating an invitation.",
  unavailable: "This invitation link is invalid, expired, revoked, or already used. Ask the inviter for a new link.",
  universityAdmin: "University Admin",
  verifyCreated: "Check your email and verify your address. Then reopen the original private invitation link and sign in to accept it.",
  verifyExisting: "Your email is not verified yet. We sent another verification link. After verifying, reopen the original private invitation link to finish.",
} as const;
